heroes=["Rajkumar","Rajkumar","Shahrukh","Vishwasya","Sampatham","Darshan","Punith"]
# print(heroes.index("Shahrukh"))
# print(heroes.count("Rajkumar"))
# print("Saaho" in heroes)
# heroes.append("Anantha")
# heroes.insert(2,"Yappia")
# heroes.remove("Darshan")
# heroes.clear()
# heroes.pop()
# heroes.pop()
# heroes.sort()
# print(heroes)
numbers=[3,24,34,564,654,32,2,21,1]
# numbers.sort()
# numbers.reverse()
# print(numbers)
# numbers_copy=numbers.copy()
# print(numbers_copy)
heroes.extend(numbers)
print(heroes)
