# mobile=input("Mobile_number")
# print("Mobile Number"+mobile)
# emailid=input("Enter your email id")
# print(emailid)
name=input("Name ")
print(name)
loc=input("Enter location ")
print(loc)
college=input("College name ")
print(college)
print(name+ " from " +loc+ " is studying at " +college)